### ISSUE TITLE
Version constraint guzzlehttp/guzzle

### ISSUE THREAD

**Issue by swimmer-zone** [EmicoEcommerce/RobinHqLib#7]
This module requires a version of GuzzleHTTP which is not compatible with Magento 2.4.4, because of this the module is not installable.

Current situation:
```
  "require": {
    "php": "~7.0",
    "guzzlehttp/guzzle": "^6.3",
    ...
  },
```

Desired situation:
```
  "require": {
    "php": "~7.0",
    "guzzlehttp/guzzle": "^6.3|^7.0",
    ...
  },
```

Magento uses `^7.3.0` as a version constraint.

**Comment by stijnbernards** [comment]
Hi @swimmer-zone this has been fixed by bumping the entire guzzle requirement to ^7.3
